### ISSUE TITLE
alt-S seems to send "post"  to the current page before switching

### ISSUE THREAD

**Issue by CADbloke** [harshayburadkar/clut-chrome-extension#1]
I've noticed odd behaviour when on an SMF-powered forum (http://www.theswamp.org in this case), when I press alt-S, the standard shortcut to switch tabs, it triggers a post / submit and posts a reply on the forum page

here's the html of the element it triggers 

``` html
<input type="submit" name="post" value="Post" onclick="return submitThisOnce(this);" accesskey="s" tabindex="2" class="button_submit">
```

...oh, wait, I see. `accesskey="s"`, that looks familiar. Hrm. Hey, I'll leave this here anyway as a warning to others. I changed the CLUT shortcut to alt-Q so now I just quit all sorts of apps accidentally by habit.

cheers for writing this.

**Comment by harshayburadkar** [comment]
CADbloke confirmed above that the behavior was due to the website itself which he was visiting. The website, had a shortcut which happened to be same as his tab switching key S. Hence closing this issue.
