### ISSUE TITLE
Any plans to port this to firefox?

### ISSUE THREAD

**Issue by HaHalit** [harshayburadkar/clut-chrome-extension#13]
Chrome is making some headlines lately about their Manifest v3 and stopping adblockers from working. This created an uproar on reddit and i'm seeing a lot of people are switching back to firefox.

Would be cool to see this extension on firefox :D thanks for making it as i've been using it daily for a long long time

**Comment by RS-DU34** [comment]
@HaHalit .... that makes no sense, this extension basically just changes Chrome so that it behaves like Firefox, which already cycles through most recently used tabs by default.

**Comment by HaHalit** [comment]
Didn’t know that

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: ***@***.***>
Sendt: mandag 28. august 2023 kl. 15:49
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [harshayburadkar/clut-chrome-extension] Any plans to port this to firefox? (Issue #13)


@HaHalit<https://github.com/HaHalit> .... that makes no sense, this extension basically just changes Chrome so that it behaves like Firefox, which already cycles through most recently used tabs by default.

**Comment by harshayburadkar** [comment]
No such current plan. I don't use FF and also I was also under the impression that FF supports this out of the box.
