### ISSUE TITLE
where are the extension's options

### ISSUE THREAD

**Issue by louisdoe** [harshayburadkar/clut-chrome-extension#14]
Hey

I can't find the "options" in CLUT, can you help?
You mention "Keys can be changed in keyboard shortcut settings on the Chrome extensions page.", but can't find it.

Thanks

Ubuntu Linux 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Chrome Version 106.0.5249.119

![image](https://user-images.githubusercontent.com/4015755/210523747-256aa833-f629-4abf-bbec-790427b43ab8.png)

**Comment by harshayburadkar** [comment]
This answer has some step by step info.
https://superuser.com/a/762887

Hope it helps you.
