### ISSUE TITLE
Suggestion for tracking clicks on read me

### ISSUE THREAD

**Issue by adityavarma1234** [harshayburadkar/clut-chrome-extension#2]
You can use goo.gl to track number of clicks. Advantages and disadvantages in wiki [here](https://www.quora.com/Which-URL-shortening-service-is-better-Goo-gl-or-Bitly)

**Comment by harshayburadkar** [comment]
Sorry I am not interested in tracking those clicks but thank you for the suggestion about goo.gl. I was thinking to add simple anonymous usage tracking to fine tune any extension behaviour but did not end up doing it. I see a lot of websites keep tracking you, so want to give that a break wherever possible.
