### ISSUE TITLE
Settings page missing

### ISSUE THREAD

**Issue by borekb** [harshayburadkar/clut-chrome-extension#4]
In Chrome 24, I don't see an option to enter extension settings, e.g., to change the default key map:

![image](https://cloud.githubusercontent.com/assets/101152/20029051/1b110182-a342-11e6-9b26-322a94b2fa7c.png)

**Comment by borekb** [comment]
Sorry, it's at the bottom of the page, I didn't know that..

**Comment by AlexanderMur** [comment]
Me too... Chrome 70 
![5778d70b18](https://user-images.githubusercontent.com/9999654/47253844-af776d80-d472-11e8-87ff-5cf3bd632cbe.jpg)

**Comment by alexandre-g** [comment]
Chrome you are ridiculous

**Comment by harshayburadkar** [comment]
This is the new place to access Keyboard shortcuts for Chrome extensions.

<img width="1083" alt="shortcuts" src="https://user-images.githubusercontent.com/1571467/48900442-63a45380-ee78-11e8-87dc-d37cf6951464.png">

<img width="985" alt="screen shot 2018-11-22 at 5 03 43 pm" src="https://user-images.githubusercontent.com/1571467/48900622-de6d6e80-ee78-11e8-83c5-a4a31686e8ae.png">
