### ISSUE TITLE
[PRIVACY] Please remove Google Analytics

### ISSUE THREAD

**Issue by roblav96** [harshayburadkar/clut-chrome-extension#5]
@harshayburadkar 
I know this repo hasn't been touched since 2016, but the times have changed quite a bit and I think the users of this extension should be aware that you have Google Analytics with tracking enabled on every single website they visit. :/

Super useful extension none the less. lol :D

**Comment by harshayburadkar** [comment]
Wait, what? Ask questions first if you don't understand enough, before assuming things (and making tall claims), esp. when you are an engineer yourself.
The extension does not track ANYTHING related to the websites the users visit. I have only set the extension to track if the extension is being used actively or is lying dormant but installed. It just shows me, e.g. 5000 users used it in the last week. 
If I wanted to track what sites users are visiting, I wouldn't have made it open source in the first place.
