### ISSUE TITLE
Any hack to update Alt+S to Ctrl+Tab?

### ISSUE THREAD

**Issue by boardtc** [harshayburadkar/clut-chrome-extension#6]
Has anyone successfully updated the keyboard shortcut from Alt+S to Ctrl+Tab? The later now works in Firefox without an extension when enabled in settings.

**Comment by harshayburadkar** [comment]
Sure, I use the default shortcuts since it's not possible without external tools or settings from within Chrome. But you can look for some ideas in this post on Superuser. 
[Switching back to last *used* tab on Chrome](https://superuser.com/q/402095)

**Comment by boardtc** [comment]
Thanks. I had voted for that question already too :-) Recent Tabs extension does not allow Ctrl+Tab & I could not get the CLUT one to work as outlined. I 'll have a look again at the others.
